name: Style Checkers
on:
  # run tests on push to master, but not when other branches are pushed to
  push:
    branches:
      - master

  # run tests for pull requests to master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - uses: docker://golangci/golangci-lint:v1.23.8
        with:
          args: golangci-lint run --disable unused,errcheck,ineffassign,staticcheck,gosimple
        env:
          CGO_ENABLED: 0
