name: Build and tests
on:
  # run tests on push to master, but not when other branches are pushed to
  push:
    branches:
      - master

  # run tests for pull requests to master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version:
          - 1.14.x
          - 1.15.x
    runs-on: ubuntu-latest

    env:
      GOPROXY: https://proxy.golang.org

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          CGO_ENABLED=0 go build

      - name: Run tests
        run: |
          CGO_ENABLED=0 go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v1

      - uses: docker://golangci/golangci-lint:latest
        with:
          args: golangci-lint run --disable unused,errcheck,ineffassign,staticcheck,gosimple
        env:
          CGO_ENABLED: 0
